### PR TITLE
Ana

### PR DESCRIPTION
**Pull request by anamariacercel**
Added 2 unit tests & some minor changes for onlongpress(). Check if it's okay now.

### CODE REVIEW

**Review by IrinaButu2307 — COMMENTED** [review]
Improvement needed: 
 let's change TripDetailFragment with a DetailsTripActivity for a smoother Bundle sending for on long press

**Review by AndreiOvidiuCiobanu — COMMENTED** [review]
Well done. These were some necessary improvements. From my side it's ok now. Let's find out what @andreihrs is going to say than I will accept your pull request

**Comment by andreihrs** [comment]
Well done, Ana. Irina has a great suggestion, we should add that to the issues log

**Review by andreihrs — APPROVED** [review]
Great improvements, Ana. @IrinaButu2307 is right, we should definitely add that suggestion to the issues log

**Pull request merged**
